import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from .checksec import detect_runsec
from .errors import KphelperError
from .findings import RuntimeProbeReport
from .qemu import load_qemu_run
from .symbols import (
    DEFAULT_SYMBOLS,
    KASLR_ANCHORS,
    calculate_kaslr_slide,
    extract_symbols,
    render_symbol_assignments,
    render_symbol_offsets,
)


DEFAULT_RUNTIME_REPORT = Path(".kphelper/runtime-report.json")
DEFAULT_RUNTIME_HEADER = Path(".kphelper/runtime-symbols.h")
RUNTIME_REPORT_VERSION = 1


def _sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _file_fingerprint(path):
    if path is None:
        return None
    path = Path(path)
    if not path.is_file():
        return {"path": str(path.resolve()), "missing": True}
    stat_result = path.stat()
    return {
        "path": str(path.resolve()),
        "size": stat_result.st_size,
        "mtime_ns": stat_result.st_mtime_ns,
        "sha256": _sha256(path),
    }


def build_run_fingerprint(run_path):
    run_path = Path(run_path)
    if not run_path.is_file():
        raise KphelperError("cannot fingerprint missing QEMU startup script: %s" % run_path)
    config = load_qemu_run(run_path)
    kernel = config.resolve_file(config.kernel)
    initrd = config.resolve_file(config.initrd)
    payload = {
        "run": _file_fingerprint(run_path),
        "kernel": _file_fingerprint(kernel),
        "initrd": _file_fingerprint(initrd),
        "cmdline": config.cmdline,
        "qemu_arguments": list(config.arguments),
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload["digest"] = hashlib.sha256(encoded).hexdigest()
    return payload


def build_kaslr_metadata(run_path, runtime_symbols):
    state = detect_runsec(run_path)["KASLR"].status
    runtime_anchor = next(
        (name for name in KASLR_ANCHORS if runtime_symbols.get(name)),
        None,
    )
    offsets = {}
    if runtime_anchor:
        anchor_address = runtime_symbols[runtime_anchor]
        offsets = {
            name: address - anchor_address
            for name, address in runtime_symbols.items()
            if name not in KASLR_ANCHORS
        }

    static_symbols = {}
    static_file = None
    try:
        static_file, static_symbols = extract_symbols(
            None,
            tuple(dict.fromkeys(tuple(runtime_symbols) + KASLR_ANCHORS)),
        )
    except KphelperError:
        pass
    anchor, slide = calculate_kaslr_slide(runtime_symbols, static_symbols)
    if slide is not None:
        state = "Enabled" if slide else "Disabled"

    if state == "Disabled":
        detail = "absolute addresses are reusable for the matching kernel and boot configuration"
    elif state == "Enabled":
        detail = "absolute addresses and slide are current-boot only; relative symbol offsets are reusable"
    else:
        detail = "KASLR state is unknown; treat absolute addresses as current-boot only"

    result = {
        "status": state,
        "detail": detail,
        "absolute_addresses_reusable": state == "Disabled",
        "offsets": offsets,
    }
    if runtime_anchor:
        result["offset_anchor"] = runtime_anchor
        result["runtime_anchor"] = runtime_symbols[runtime_anchor]
    if slide is not None:
        result.update({"anchor": anchor, "slide": slide})
    if static_file:
        result["vmlinux"] = str(Path(static_file).resolve())
    return result


def _serialize_runtime(report):
    return {
        name: finding.to_dict()
        for name, finding in report.findings.items()
    }


def _write_atomic(path, content):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def _render_header(symbols, kaslr):
    lines = [
        "/* Generated by kphelper. Runtime addresses may be boot-specific. */",
        render_symbol_assignments(symbols, DEFAULT_SYMBOLS),
    ]
    offsets = kaslr.get("offsets") or {}
    if offsets:
        lines.extend([
            "",
            "/* Stable offsets relative to %s. */" % kaslr["offset_anchor"],
            render_symbol_offsets(offsets, DEFAULT_SYMBOLS, kaslr["offset_anchor"]),
        ])
    return "\n".join(lines) + "\n"


def save_runtime_report(
    live_result,
    run_path,
    analysis=False,
    report_path=DEFAULT_RUNTIME_REPORT,
    header_path=DEFAULT_RUNTIME_HEADER,
):
    report = RuntimeProbeReport.from_mapping(live_result)
    symbols = {name: int(value) for name, value in report.symbols.items()}
    kaslr = build_kaslr_metadata(run_path, symbols)
    payload = {
        "schema_version": RUNTIME_REPORT_VERSION,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source": {
            "kind": "analysis" if analysis else "local",
            "run": str(Path(run_path).resolve()),
        },
        "fingerprint": build_run_fingerprint(run_path),
        "runtime": _serialize_runtime(report),
        "symbols": symbols,
        "kaslr": kaslr,
    }
    _write_atomic(report_path, json.dumps(payload, indent=2, sort_keys=True) + "\n")
    _write_atomic(header_path, _render_header(symbols, kaslr))
    return payload


def load_runtime_report(report_path=DEFAULT_RUNTIME_REPORT, validate=True):
    report_path = Path(report_path)
    try:
        payload = json.loads(report_path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise KphelperError(
            "runtime report not found; run: kphelper checksec --all"
        ) from error
    except (OSError, ValueError) as error:
        raise KphelperError("invalid runtime report: %s" % report_path) from error
    if payload.get("schema_version") != RUNTIME_REPORT_VERSION:
        raise KphelperError("unsupported runtime report version; refresh runtime symbols")
    if validate:
        run_path = payload.get("source", {}).get("run")
        if not run_path:
            raise KphelperError("runtime report has no source run script; refresh runtime symbols")
        current = build_run_fingerprint(run_path)
        if current["digest"] != payload.get("fingerprint", {}).get("digest"):
            raise KphelperError(
                "runtime report is stale because the QEMU configuration changed; use: kphelper symbols --refresh"
            )
    return payload
